baseURL: "https://first-pages--bronze-guidelines.netlify.app"

title: Quire Starter
languageCode: en-us
theme: default
publishDir: site

footnoteReturnLinkContents: '↩'
GoogleAnalytics: ''

pluralizeListTitles: true
disableKinds:
  - home
  - section
  - taxonomy
  - term

quire_credit_line: This publication was created using [Quire](https://quire.getty.edu)™, a multiformat publishing tool from Getty.

params:
  biblioHeading: Bibliography
  citationPageLocationDivider: ', '
  citationPopupStyle: text # text | icon
  contributorByline: name-title # name | name-title | false
  displayBiblioShort: true
  entryPageObjectLinkText: View in Collection
  entryPageSideBySideLayout: false
  figureLabelLocation: below # below | on-top
  figureModal: true
  figureModalIcons: true
  figureZoom: true
  imageDir: '/_assets/images'
  licenseIcons: true
  menuType: full
  nextPageButtonText: Next
  pageLabelDivider: '. '
  pageContributorDivider: " — "
  prevPageButtonText: Back
  searchEnabled: true
  tocType: full
